// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package stores

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yiran15/api-server/model"
)

func newFeiShuUser(db *gorm.DB, opts ...gen.DOOption) feiShuUser {
	_feiShuUser := feiShuUser{}

	_feiShuUser.feiShuUserDo.UseDB(db, opts...)
	_feiShuUser.feiShuUserDo.UseModel(&model.FeiShuUser{})

	tableName := _feiShuUser.feiShuUserDo.TableName()
	_feiShuUser.ALL = field.NewAsterisk(tableName)
	_feiShuUser.UID = field.NewInt64(tableName, "uid")
	_feiShuUser.CreatedAt = field.NewTime(tableName, "created_at")
	_feiShuUser.UpdatedAt = field.NewTime(tableName, "updated_at")
	_feiShuUser.DeletedAt = field.NewField(tableName, "deleted_at")
	_feiShuUser.AvatarBig = field.NewString(tableName, "avatar_big")
	_feiShuUser.AvatarMiddle = field.NewString(tableName, "avatar_middle")
	_feiShuUser.AvatarThumb = field.NewString(tableName, "avatar_thumb")
	_feiShuUser.AvatarUrl = field.NewString(tableName, "avatar_url")
	_feiShuUser.Email = field.NewString(tableName, "email")
	_feiShuUser.EmployeeNo = field.NewString(tableName, "employee_no")
	_feiShuUser.EnName = field.NewString(tableName, "en_name")
	_feiShuUser.EnterpriseEmail = field.NewString(tableName, "enterprise_email")
	_feiShuUser.Mobile = field.NewString(tableName, "mobile")
	_feiShuUser.Name = field.NewString(tableName, "name")
	_feiShuUser.OpenID = field.NewString(tableName, "open_id")
	_feiShuUser.TenantKey = field.NewString(tableName, "tenant_key")
	_feiShuUser.UnionID = field.NewString(tableName, "union_id")
	_feiShuUser.UserID = field.NewString(tableName, "user_id")
	_feiShuUser.User = feiShuUserBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "model.User"),
		Roles: struct {
			field.RelationField
			Users struct {
				field.RelationField
			}
			Apis struct {
				field.RelationField
				Roles struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("User.Roles", "model.Role"),
			Users: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Roles.Users", "model.User"),
			},
			Apis: struct {
				field.RelationField
				Roles struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("User.Roles.Apis", "model.Api"),
				Roles: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.Roles.Apis.Roles", "model.Role"),
				},
			},
		},
	}

	_feiShuUser.fillFieldMap()

	return _feiShuUser
}

type feiShuUser struct {
	feiShuUserDo

	ALL             field.Asterisk
	UID             field.Int64 // 关联users表中的用户id
	CreatedAt       field.Time
	UpdatedAt       field.Time
	DeletedAt       field.Field
	AvatarBig       field.String // 飞书用户avatar_big
	AvatarMiddle    field.String // 飞书用户avatar_middle
	AvatarThumb     field.String // 飞书用户avatar_thumb
	AvatarUrl       field.String // 飞书用户avatar_url
	Email           field.String // 飞书用户email
	EmployeeNo      field.String // 飞书用户employee_no
	EnName          field.String // 飞书用户en_name
	EnterpriseEmail field.String // 飞书用户enterprise_email
	Mobile          field.String // 飞书用户mobile
	Name            field.String // 飞书用户name
	OpenID          field.String // 飞书用户open_id
	TenantKey       field.String // 飞书用户tenant_key
	UnionID         field.String // 飞书用户union_id
	UserID          field.String // 飞书用户ID
	User            feiShuUserBelongsToUser

	fieldMap map[string]field.Expr
}

func (f feiShuUser) Table(newTableName string) *feiShuUser {
	f.feiShuUserDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f feiShuUser) As(alias string) *feiShuUser {
	f.feiShuUserDo.DO = *(f.feiShuUserDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *feiShuUser) updateTableName(table string) *feiShuUser {
	f.ALL = field.NewAsterisk(table)
	f.UID = field.NewInt64(table, "uid")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")
	f.DeletedAt = field.NewField(table, "deleted_at")
	f.AvatarBig = field.NewString(table, "avatar_big")
	f.AvatarMiddle = field.NewString(table, "avatar_middle")
	f.AvatarThumb = field.NewString(table, "avatar_thumb")
	f.AvatarUrl = field.NewString(table, "avatar_url")
	f.Email = field.NewString(table, "email")
	f.EmployeeNo = field.NewString(table, "employee_no")
	f.EnName = field.NewString(table, "en_name")
	f.EnterpriseEmail = field.NewString(table, "enterprise_email")
	f.Mobile = field.NewString(table, "mobile")
	f.Name = field.NewString(table, "name")
	f.OpenID = field.NewString(table, "open_id")
	f.TenantKey = field.NewString(table, "tenant_key")
	f.UnionID = field.NewString(table, "union_id")
	f.UserID = field.NewString(table, "user_id")

	f.fillFieldMap()

	return f
}

func (f *feiShuUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *feiShuUser) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 19)
	f.fieldMap["uid"] = f.UID
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["deleted_at"] = f.DeletedAt
	f.fieldMap["avatar_big"] = f.AvatarBig
	f.fieldMap["avatar_middle"] = f.AvatarMiddle
	f.fieldMap["avatar_thumb"] = f.AvatarThumb
	f.fieldMap["avatar_url"] = f.AvatarUrl
	f.fieldMap["email"] = f.Email
	f.fieldMap["employee_no"] = f.EmployeeNo
	f.fieldMap["en_name"] = f.EnName
	f.fieldMap["enterprise_email"] = f.EnterpriseEmail
	f.fieldMap["mobile"] = f.Mobile
	f.fieldMap["name"] = f.Name
	f.fieldMap["open_id"] = f.OpenID
	f.fieldMap["tenant_key"] = f.TenantKey
	f.fieldMap["union_id"] = f.UnionID
	f.fieldMap["user_id"] = f.UserID

}

func (f feiShuUser) clone(db *gorm.DB) feiShuUser {
	f.feiShuUserDo.ReplaceConnPool(db.Statement.ConnPool)
	f.User.db = db.Session(&gorm.Session{Initialized: true})
	f.User.db.Statement.ConnPool = db.Statement.ConnPool
	return f
}

func (f feiShuUser) replaceDB(db *gorm.DB) feiShuUser {
	f.feiShuUserDo.ReplaceDB(db)
	f.User.db = db.Session(&gorm.Session{})
	return f
}

type feiShuUserBelongsToUser struct {
	db *gorm.DB

	field.RelationField

	Roles struct {
		field.RelationField
		Users struct {
			field.RelationField
		}
		Apis struct {
			field.RelationField
			Roles struct {
				field.RelationField
			}
		}
	}
}

func (a feiShuUserBelongsToUser) Where(conds ...field.Expr) *feiShuUserBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a feiShuUserBelongsToUser) WithContext(ctx context.Context) *feiShuUserBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a feiShuUserBelongsToUser) Session(session *gorm.Session) *feiShuUserBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a feiShuUserBelongsToUser) Model(m *model.FeiShuUser) *feiShuUserBelongsToUserTx {
	return &feiShuUserBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a feiShuUserBelongsToUser) Unscoped() *feiShuUserBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type feiShuUserBelongsToUserTx struct{ tx *gorm.Association }

func (a feiShuUserBelongsToUserTx) Find() (result *model.User, err error) {
	return result, a.tx.Find(&result)
}

func (a feiShuUserBelongsToUserTx) Append(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a feiShuUserBelongsToUserTx) Replace(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a feiShuUserBelongsToUserTx) Delete(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a feiShuUserBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a feiShuUserBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a feiShuUserBelongsToUserTx) Unscoped() *feiShuUserBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type feiShuUserDo struct{ gen.DO }

type IFeiShuUserDo interface {
	gen.SubQuery
	Debug() IFeiShuUserDo
	WithContext(ctx context.Context) IFeiShuUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFeiShuUserDo
	WriteDB() IFeiShuUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFeiShuUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFeiShuUserDo
	Not(conds ...gen.Condition) IFeiShuUserDo
	Or(conds ...gen.Condition) IFeiShuUserDo
	Select(conds ...field.Expr) IFeiShuUserDo
	Where(conds ...gen.Condition) IFeiShuUserDo
	Order(conds ...field.Expr) IFeiShuUserDo
	Distinct(cols ...field.Expr) IFeiShuUserDo
	Omit(cols ...field.Expr) IFeiShuUserDo
	Join(table schema.Tabler, on ...field.Expr) IFeiShuUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFeiShuUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFeiShuUserDo
	Group(cols ...field.Expr) IFeiShuUserDo
	Having(conds ...gen.Condition) IFeiShuUserDo
	Limit(limit int) IFeiShuUserDo
	Offset(offset int) IFeiShuUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFeiShuUserDo
	Unscoped() IFeiShuUserDo
	Create(values ...*model.FeiShuUser) error
	CreateInBatches(values []*model.FeiShuUser, batchSize int) error
	Save(values ...*model.FeiShuUser) error
	First() (*model.FeiShuUser, error)
	Take() (*model.FeiShuUser, error)
	Last() (*model.FeiShuUser, error)
	Find() ([]*model.FeiShuUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FeiShuUser, err error)
	FindInBatches(result *[]*model.FeiShuUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FeiShuUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFeiShuUserDo
	Assign(attrs ...field.AssignExpr) IFeiShuUserDo
	Joins(fields ...field.RelationField) IFeiShuUserDo
	Preload(fields ...field.RelationField) IFeiShuUserDo
	FirstOrInit() (*model.FeiShuUser, error)
	FirstOrCreate() (*model.FeiShuUser, error)
	FindByPage(offset int, limit int) (result []*model.FeiShuUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFeiShuUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	FilterWithID(id int) (result model.FeiShuUser, err error)
}

// SELECT * FROM @@table WHERE name = @id
func (f feiShuUserDo) FilterWithID(id int) (result model.FeiShuUser, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM feishu_users WHERE name = ? ")

	var executeSQL *gorm.DB
	executeSQL = f.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (f feiShuUserDo) Debug() IFeiShuUserDo {
	return f.withDO(f.DO.Debug())
}

func (f feiShuUserDo) WithContext(ctx context.Context) IFeiShuUserDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f feiShuUserDo) ReadDB() IFeiShuUserDo {
	return f.Clauses(dbresolver.Read)
}

func (f feiShuUserDo) WriteDB() IFeiShuUserDo {
	return f.Clauses(dbresolver.Write)
}

func (f feiShuUserDo) Session(config *gorm.Session) IFeiShuUserDo {
	return f.withDO(f.DO.Session(config))
}

func (f feiShuUserDo) Clauses(conds ...clause.Expression) IFeiShuUserDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f feiShuUserDo) Returning(value interface{}, columns ...string) IFeiShuUserDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f feiShuUserDo) Not(conds ...gen.Condition) IFeiShuUserDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f feiShuUserDo) Or(conds ...gen.Condition) IFeiShuUserDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f feiShuUserDo) Select(conds ...field.Expr) IFeiShuUserDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f feiShuUserDo) Where(conds ...gen.Condition) IFeiShuUserDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f feiShuUserDo) Order(conds ...field.Expr) IFeiShuUserDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f feiShuUserDo) Distinct(cols ...field.Expr) IFeiShuUserDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f feiShuUserDo) Omit(cols ...field.Expr) IFeiShuUserDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f feiShuUserDo) Join(table schema.Tabler, on ...field.Expr) IFeiShuUserDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f feiShuUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFeiShuUserDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f feiShuUserDo) RightJoin(table schema.Tabler, on ...field.Expr) IFeiShuUserDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f feiShuUserDo) Group(cols ...field.Expr) IFeiShuUserDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f feiShuUserDo) Having(conds ...gen.Condition) IFeiShuUserDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f feiShuUserDo) Limit(limit int) IFeiShuUserDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f feiShuUserDo) Offset(offset int) IFeiShuUserDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f feiShuUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFeiShuUserDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f feiShuUserDo) Unscoped() IFeiShuUserDo {
	return f.withDO(f.DO.Unscoped())
}

func (f feiShuUserDo) Create(values ...*model.FeiShuUser) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f feiShuUserDo) CreateInBatches(values []*model.FeiShuUser, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f feiShuUserDo) Save(values ...*model.FeiShuUser) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f feiShuUserDo) First() (*model.FeiShuUser, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FeiShuUser), nil
	}
}

func (f feiShuUserDo) Take() (*model.FeiShuUser, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FeiShuUser), nil
	}
}

func (f feiShuUserDo) Last() (*model.FeiShuUser, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FeiShuUser), nil
	}
}

func (f feiShuUserDo) Find() ([]*model.FeiShuUser, error) {
	result, err := f.DO.Find()
	return result.([]*model.FeiShuUser), err
}

func (f feiShuUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FeiShuUser, err error) {
	buf := make([]*model.FeiShuUser, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f feiShuUserDo) FindInBatches(result *[]*model.FeiShuUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f feiShuUserDo) Attrs(attrs ...field.AssignExpr) IFeiShuUserDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f feiShuUserDo) Assign(attrs ...field.AssignExpr) IFeiShuUserDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f feiShuUserDo) Joins(fields ...field.RelationField) IFeiShuUserDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f feiShuUserDo) Preload(fields ...field.RelationField) IFeiShuUserDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f feiShuUserDo) FirstOrInit() (*model.FeiShuUser, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FeiShuUser), nil
	}
}

func (f feiShuUserDo) FirstOrCreate() (*model.FeiShuUser, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FeiShuUser), nil
	}
}

func (f feiShuUserDo) FindByPage(offset int, limit int) (result []*model.FeiShuUser, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f feiShuUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f feiShuUserDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f feiShuUserDo) Delete(models ...*model.FeiShuUser) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *feiShuUserDo) withDO(do gen.Dao) *feiShuUserDo {
	f.DO = *do.(*gen.DO)
	return f
}
