// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package stores

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q          = new(Query)
	Api        *api
	CasbinRule *casbinRule
	Oauth2User *oauth2User
	OauthUser  *oauthUser
	Role       *role
	User       *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Api = &Q.Api
	CasbinRule = &Q.CasbinRule
	Oauth2User = &Q.Oauth2User
	OauthUser = &Q.OauthUser
	Role = &Q.Role
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:         db,
		Api:        newApi(db, opts...),
		CasbinRule: newCasbinRule(db, opts...),
		Oauth2User: newOauth2User(db, opts...),
		OauthUser:  newOauthUser(db, opts...),
		Role:       newRole(db, opts...),
		User:       newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Api        api
	CasbinRule casbinRule
	Oauth2User oauth2User
	OauthUser  oauthUser
	Role       role
	User       user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		Api:        q.Api.clone(db),
		CasbinRule: q.CasbinRule.clone(db),
		Oauth2User: q.Oauth2User.clone(db),
		OauthUser:  q.OauthUser.clone(db),
		Role:       q.Role.clone(db),
		User:       q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		Api:        q.Api.replaceDB(db),
		CasbinRule: q.CasbinRule.replaceDB(db),
		Oauth2User: q.Oauth2User.replaceDB(db),
		OauthUser:  q.OauthUser.replaceDB(db),
		Role:       q.Role.replaceDB(db),
		User:       q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Api        IApiDo
	CasbinRule ICasbinRuleDo
	Oauth2User IOauth2UserDo
	OauthUser  IOauthUserDo
	Role       IRoleDo
	User       IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Api:        q.Api.WithContext(ctx),
		CasbinRule: q.CasbinRule.WithContext(ctx),
		Oauth2User: q.Oauth2User.WithContext(ctx),
		OauthUser:  q.OauthUser.WithContext(ctx),
		Role:       q.Role.WithContext(ctx),
		User:       q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
