// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package stores

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yiran15/api-server/model"
)

func newOauthUser(db *gorm.DB, opts ...gen.DOOption) oauthUser {
	_oauthUser := oauthUser{}

	_oauthUser.oauthUserDo.UseDB(db, opts...)
	_oauthUser.oauthUserDo.UseModel(&model.OauthUser{})

	tableName := _oauthUser.oauthUserDo.TableName()
	_oauthUser.ALL = field.NewAsterisk(tableName)
	_oauthUser.UID = field.NewInt64(tableName, "uid")
	_oauthUser.CreatedAt = field.NewTime(tableName, "created_at")
	_oauthUser.UpdatedAt = field.NewTime(tableName, "updated_at")
	_oauthUser.DeletedAt = field.NewField(tableName, "deleted_at")
	_oauthUser.AvatarBig = field.NewString(tableName, "avatar_big")
	_oauthUser.AvatarMiddle = field.NewString(tableName, "avatar_middle")
	_oauthUser.AvatarThumb = field.NewString(tableName, "avatar_thumb")
	_oauthUser.AvatarUrl = field.NewString(tableName, "avatar_url")
	_oauthUser.Email = field.NewString(tableName, "email")
	_oauthUser.EmployeeNo = field.NewString(tableName, "employee_no")
	_oauthUser.EnName = field.NewString(tableName, "en_name")
	_oauthUser.EnterpriseEmail = field.NewString(tableName, "enterprise_email")
	_oauthUser.Mobile = field.NewString(tableName, "mobile")
	_oauthUser.Name = field.NewString(tableName, "name")
	_oauthUser.OpenID = field.NewString(tableName, "open_id")
	_oauthUser.TenantKey = field.NewString(tableName, "tenant_key")
	_oauthUser.UnionID = field.NewString(tableName, "union_id")
	_oauthUser.UserID = field.NewString(tableName, "user_id")
	_oauthUser.User = oauthUserBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "model.User"),
		Roles: struct {
			field.RelationField
			Users struct {
				field.RelationField
			}
			Apis struct {
				field.RelationField
				Roles struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("User.Roles", "model.Role"),
			Users: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Roles.Users", "model.User"),
			},
			Apis: struct {
				field.RelationField
				Roles struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("User.Roles.Apis", "model.Api"),
				Roles: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.Roles.Apis.Roles", "model.Role"),
				},
			},
		},
	}

	_oauthUser.fillFieldMap()

	return _oauthUser
}

type oauthUser struct {
	oauthUserDo

	ALL             field.Asterisk
	UID             field.Int64 // 关联users表中的用户id
	CreatedAt       field.Time
	UpdatedAt       field.Time
	DeletedAt       field.Field
	AvatarBig       field.String // 飞书用户avatar_big
	AvatarMiddle    field.String // 飞书用户avatar_middle
	AvatarThumb     field.String // 飞书用户avatar_thumb
	AvatarUrl       field.String // 飞书用户avatar_url
	Email           field.String // 飞书用户email
	EmployeeNo      field.String // 飞书用户employee_no
	EnName          field.String // 飞书用户en_name
	EnterpriseEmail field.String // 飞书用户enterprise_email
	Mobile          field.String // 飞书用户mobile
	Name            field.String // 飞书用户name
	OpenID          field.String // 飞书用户open_id
	TenantKey       field.String // 飞书用户tenant_key
	UnionID         field.String // 飞书用户union_id
	UserID          field.String // 飞书用户ID
	User            oauthUserBelongsToUser

	fieldMap map[string]field.Expr
}

func (o oauthUser) Table(newTableName string) *oauthUser {
	o.oauthUserDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o oauthUser) As(alias string) *oauthUser {
	o.oauthUserDo.DO = *(o.oauthUserDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *oauthUser) updateTableName(table string) *oauthUser {
	o.ALL = field.NewAsterisk(table)
	o.UID = field.NewInt64(table, "uid")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")
	o.DeletedAt = field.NewField(table, "deleted_at")
	o.AvatarBig = field.NewString(table, "avatar_big")
	o.AvatarMiddle = field.NewString(table, "avatar_middle")
	o.AvatarThumb = field.NewString(table, "avatar_thumb")
	o.AvatarUrl = field.NewString(table, "avatar_url")
	o.Email = field.NewString(table, "email")
	o.EmployeeNo = field.NewString(table, "employee_no")
	o.EnName = field.NewString(table, "en_name")
	o.EnterpriseEmail = field.NewString(table, "enterprise_email")
	o.Mobile = field.NewString(table, "mobile")
	o.Name = field.NewString(table, "name")
	o.OpenID = field.NewString(table, "open_id")
	o.TenantKey = field.NewString(table, "tenant_key")
	o.UnionID = field.NewString(table, "union_id")
	o.UserID = field.NewString(table, "user_id")

	o.fillFieldMap()

	return o
}

func (o *oauthUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *oauthUser) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 19)
	o.fieldMap["uid"] = o.UID
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["deleted_at"] = o.DeletedAt
	o.fieldMap["avatar_big"] = o.AvatarBig
	o.fieldMap["avatar_middle"] = o.AvatarMiddle
	o.fieldMap["avatar_thumb"] = o.AvatarThumb
	o.fieldMap["avatar_url"] = o.AvatarUrl
	o.fieldMap["email"] = o.Email
	o.fieldMap["employee_no"] = o.EmployeeNo
	o.fieldMap["en_name"] = o.EnName
	o.fieldMap["enterprise_email"] = o.EnterpriseEmail
	o.fieldMap["mobile"] = o.Mobile
	o.fieldMap["name"] = o.Name
	o.fieldMap["open_id"] = o.OpenID
	o.fieldMap["tenant_key"] = o.TenantKey
	o.fieldMap["union_id"] = o.UnionID
	o.fieldMap["user_id"] = o.UserID

}

func (o oauthUser) clone(db *gorm.DB) oauthUser {
	o.oauthUserDo.ReplaceConnPool(db.Statement.ConnPool)
	o.User.db = db.Session(&gorm.Session{Initialized: true})
	o.User.db.Statement.ConnPool = db.Statement.ConnPool
	return o
}

func (o oauthUser) replaceDB(db *gorm.DB) oauthUser {
	o.oauthUserDo.ReplaceDB(db)
	o.User.db = db.Session(&gorm.Session{})
	return o
}

type oauthUserBelongsToUser struct {
	db *gorm.DB

	field.RelationField

	Roles struct {
		field.RelationField
		Users struct {
			field.RelationField
		}
		Apis struct {
			field.RelationField
			Roles struct {
				field.RelationField
			}
		}
	}
}

func (a oauthUserBelongsToUser) Where(conds ...field.Expr) *oauthUserBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a oauthUserBelongsToUser) WithContext(ctx context.Context) *oauthUserBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a oauthUserBelongsToUser) Session(session *gorm.Session) *oauthUserBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a oauthUserBelongsToUser) Model(m *model.OauthUser) *oauthUserBelongsToUserTx {
	return &oauthUserBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a oauthUserBelongsToUser) Unscoped() *oauthUserBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type oauthUserBelongsToUserTx struct{ tx *gorm.Association }

func (a oauthUserBelongsToUserTx) Find() (result *model.User, err error) {
	return result, a.tx.Find(&result)
}

func (a oauthUserBelongsToUserTx) Append(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a oauthUserBelongsToUserTx) Replace(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a oauthUserBelongsToUserTx) Delete(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a oauthUserBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a oauthUserBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a oauthUserBelongsToUserTx) Unscoped() *oauthUserBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type oauthUserDo struct{ gen.DO }

type IOauthUserDo interface {
	gen.SubQuery
	Debug() IOauthUserDo
	WithContext(ctx context.Context) IOauthUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOauthUserDo
	WriteDB() IOauthUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOauthUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOauthUserDo
	Not(conds ...gen.Condition) IOauthUserDo
	Or(conds ...gen.Condition) IOauthUserDo
	Select(conds ...field.Expr) IOauthUserDo
	Where(conds ...gen.Condition) IOauthUserDo
	Order(conds ...field.Expr) IOauthUserDo
	Distinct(cols ...field.Expr) IOauthUserDo
	Omit(cols ...field.Expr) IOauthUserDo
	Join(table schema.Tabler, on ...field.Expr) IOauthUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOauthUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOauthUserDo
	Group(cols ...field.Expr) IOauthUserDo
	Having(conds ...gen.Condition) IOauthUserDo
	Limit(limit int) IOauthUserDo
	Offset(offset int) IOauthUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOauthUserDo
	Unscoped() IOauthUserDo
	Create(values ...*model.OauthUser) error
	CreateInBatches(values []*model.OauthUser, batchSize int) error
	Save(values ...*model.OauthUser) error
	First() (*model.OauthUser, error)
	Take() (*model.OauthUser, error)
	Last() (*model.OauthUser, error)
	Find() ([]*model.OauthUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OauthUser, err error)
	FindInBatches(result *[]*model.OauthUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.OauthUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOauthUserDo
	Assign(attrs ...field.AssignExpr) IOauthUserDo
	Joins(fields ...field.RelationField) IOauthUserDo
	Preload(fields ...field.RelationField) IOauthUserDo
	FirstOrInit() (*model.OauthUser, error)
	FirstOrCreate() (*model.OauthUser, error)
	FindByPage(offset int, limit int) (result []*model.OauthUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOauthUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o oauthUserDo) Debug() IOauthUserDo {
	return o.withDO(o.DO.Debug())
}

func (o oauthUserDo) WithContext(ctx context.Context) IOauthUserDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o oauthUserDo) ReadDB() IOauthUserDo {
	return o.Clauses(dbresolver.Read)
}

func (o oauthUserDo) WriteDB() IOauthUserDo {
	return o.Clauses(dbresolver.Write)
}

func (o oauthUserDo) Session(config *gorm.Session) IOauthUserDo {
	return o.withDO(o.DO.Session(config))
}

func (o oauthUserDo) Clauses(conds ...clause.Expression) IOauthUserDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o oauthUserDo) Returning(value interface{}, columns ...string) IOauthUserDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o oauthUserDo) Not(conds ...gen.Condition) IOauthUserDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o oauthUserDo) Or(conds ...gen.Condition) IOauthUserDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o oauthUserDo) Select(conds ...field.Expr) IOauthUserDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o oauthUserDo) Where(conds ...gen.Condition) IOauthUserDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o oauthUserDo) Order(conds ...field.Expr) IOauthUserDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o oauthUserDo) Distinct(cols ...field.Expr) IOauthUserDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o oauthUserDo) Omit(cols ...field.Expr) IOauthUserDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o oauthUserDo) Join(table schema.Tabler, on ...field.Expr) IOauthUserDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o oauthUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOauthUserDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o oauthUserDo) RightJoin(table schema.Tabler, on ...field.Expr) IOauthUserDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o oauthUserDo) Group(cols ...field.Expr) IOauthUserDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o oauthUserDo) Having(conds ...gen.Condition) IOauthUserDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o oauthUserDo) Limit(limit int) IOauthUserDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o oauthUserDo) Offset(offset int) IOauthUserDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o oauthUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOauthUserDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o oauthUserDo) Unscoped() IOauthUserDo {
	return o.withDO(o.DO.Unscoped())
}

func (o oauthUserDo) Create(values ...*model.OauthUser) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o oauthUserDo) CreateInBatches(values []*model.OauthUser, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o oauthUserDo) Save(values ...*model.OauthUser) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o oauthUserDo) First() (*model.OauthUser, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.OauthUser), nil
	}
}

func (o oauthUserDo) Take() (*model.OauthUser, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.OauthUser), nil
	}
}

func (o oauthUserDo) Last() (*model.OauthUser, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.OauthUser), nil
	}
}

func (o oauthUserDo) Find() ([]*model.OauthUser, error) {
	result, err := o.DO.Find()
	return result.([]*model.OauthUser), err
}

func (o oauthUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.OauthUser, err error) {
	buf := make([]*model.OauthUser, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o oauthUserDo) FindInBatches(result *[]*model.OauthUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o oauthUserDo) Attrs(attrs ...field.AssignExpr) IOauthUserDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o oauthUserDo) Assign(attrs ...field.AssignExpr) IOauthUserDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o oauthUserDo) Joins(fields ...field.RelationField) IOauthUserDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o oauthUserDo) Preload(fields ...field.RelationField) IOauthUserDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o oauthUserDo) FirstOrInit() (*model.OauthUser, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.OauthUser), nil
	}
}

func (o oauthUserDo) FirstOrCreate() (*model.OauthUser, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.OauthUser), nil
	}
}

func (o oauthUserDo) FindByPage(offset int, limit int) (result []*model.OauthUser, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o oauthUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o oauthUserDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o oauthUserDo) Delete(models ...*model.OauthUser) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *oauthUserDo) withDO(do gen.Dao) *oauthUserDo {
	o.DO = *do.(*gen.DO)
	return o
}
