// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package stores

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yiran15/api-server/model"
)

func newOauth2User(db *gorm.DB, opts ...gen.DOOption) oauth2User {
	_oauth2User := oauth2User{}

	_oauth2User.oauth2UserDo.UseDB(db, opts...)
	_oauth2User.oauth2UserDo.UseModel(&model.Oauth2User{})

	tableName := _oauth2User.oauth2UserDo.TableName()
	_oauth2User.ALL = field.NewAsterisk(tableName)
	_oauth2User.ID = field.NewInt64(tableName, "id")
	_oauth2User.CreatedAt = field.NewTime(tableName, "created_at")
	_oauth2User.UpdatedAt = field.NewTime(tableName, "updated_at")
	_oauth2User.DeletedAt = field.NewField(tableName, "deleted_at")
	_oauth2User.Email = field.NewString(tableName, "email")
	_oauth2User.Provider = field.NewString(tableName, "provider")
	_oauth2User.Details = field.NewField(tableName, "details")
	_oauth2User.User = oauth2UserHasOneUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "model.User"),
		Roles: struct {
			field.RelationField
			Users struct {
				field.RelationField
			}
			Apis struct {
				field.RelationField
				Roles struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("User.Roles", "model.Role"),
			Users: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Roles.Users", "model.User"),
			},
			Apis: struct {
				field.RelationField
				Roles struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("User.Roles.Apis", "model.Api"),
				Roles: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.Roles.Apis.Roles", "model.Role"),
				},
			},
		},
	}

	_oauth2User.fillFieldMap()

	return _oauth2User
}

type oauth2User struct {
	oauth2UserDo

	ALL       field.Asterisk
	ID        field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	Email     field.String
	Provider  field.String
	Details   field.Field
	User      oauth2UserHasOneUser

	fieldMap map[string]field.Expr
}

func (o oauth2User) Table(newTableName string) *oauth2User {
	o.oauth2UserDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o oauth2User) As(alias string) *oauth2User {
	o.oauth2UserDo.DO = *(o.oauth2UserDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *oauth2User) updateTableName(table string) *oauth2User {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")
	o.DeletedAt = field.NewField(table, "deleted_at")
	o.Email = field.NewString(table, "email")
	o.Provider = field.NewString(table, "provider")
	o.Details = field.NewField(table, "details")

	o.fillFieldMap()

	return o
}

func (o *oauth2User) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *oauth2User) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 8)
	o.fieldMap["id"] = o.ID
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["deleted_at"] = o.DeletedAt
	o.fieldMap["email"] = o.Email
	o.fieldMap["provider"] = o.Provider
	o.fieldMap["details"] = o.Details

}

func (o oauth2User) clone(db *gorm.DB) oauth2User {
	o.oauth2UserDo.ReplaceConnPool(db.Statement.ConnPool)
	o.User.db = db.Session(&gorm.Session{Initialized: true})
	o.User.db.Statement.ConnPool = db.Statement.ConnPool
	return o
}

func (o oauth2User) replaceDB(db *gorm.DB) oauth2User {
	o.oauth2UserDo.ReplaceDB(db)
	o.User.db = db.Session(&gorm.Session{})
	return o
}

type oauth2UserHasOneUser struct {
	db *gorm.DB

	field.RelationField

	Roles struct {
		field.RelationField
		Users struct {
			field.RelationField
		}
		Apis struct {
			field.RelationField
			Roles struct {
				field.RelationField
			}
		}
	}
}

func (a oauth2UserHasOneUser) Where(conds ...field.Expr) *oauth2UserHasOneUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a oauth2UserHasOneUser) WithContext(ctx context.Context) *oauth2UserHasOneUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a oauth2UserHasOneUser) Session(session *gorm.Session) *oauth2UserHasOneUser {
	a.db = a.db.Session(session)
	return &a
}

func (a oauth2UserHasOneUser) Model(m *model.Oauth2User) *oauth2UserHasOneUserTx {
	return &oauth2UserHasOneUserTx{a.db.Model(m).Association(a.Name())}
}

func (a oauth2UserHasOneUser) Unscoped() *oauth2UserHasOneUser {
	a.db = a.db.Unscoped()
	return &a
}

type oauth2UserHasOneUserTx struct{ tx *gorm.Association }

func (a oauth2UserHasOneUserTx) Find() (result *model.User, err error) {
	return result, a.tx.Find(&result)
}

func (a oauth2UserHasOneUserTx) Append(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a oauth2UserHasOneUserTx) Replace(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a oauth2UserHasOneUserTx) Delete(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a oauth2UserHasOneUserTx) Clear() error {
	return a.tx.Clear()
}

func (a oauth2UserHasOneUserTx) Count() int64 {
	return a.tx.Count()
}

func (a oauth2UserHasOneUserTx) Unscoped() *oauth2UserHasOneUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type oauth2UserDo struct{ gen.DO }

type IOauth2UserDo interface {
	gen.SubQuery
	Debug() IOauth2UserDo
	WithContext(ctx context.Context) IOauth2UserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IOauth2UserDo
	WriteDB() IOauth2UserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IOauth2UserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IOauth2UserDo
	Not(conds ...gen.Condition) IOauth2UserDo
	Or(conds ...gen.Condition) IOauth2UserDo
	Select(conds ...field.Expr) IOauth2UserDo
	Where(conds ...gen.Condition) IOauth2UserDo
	Order(conds ...field.Expr) IOauth2UserDo
	Distinct(cols ...field.Expr) IOauth2UserDo
	Omit(cols ...field.Expr) IOauth2UserDo
	Join(table schema.Tabler, on ...field.Expr) IOauth2UserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IOauth2UserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IOauth2UserDo
	Group(cols ...field.Expr) IOauth2UserDo
	Having(conds ...gen.Condition) IOauth2UserDo
	Limit(limit int) IOauth2UserDo
	Offset(offset int) IOauth2UserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IOauth2UserDo
	Unscoped() IOauth2UserDo
	Create(values ...*model.Oauth2User) error
	CreateInBatches(values []*model.Oauth2User, batchSize int) error
	Save(values ...*model.Oauth2User) error
	First() (*model.Oauth2User, error)
	Take() (*model.Oauth2User, error)
	Last() (*model.Oauth2User, error)
	Find() ([]*model.Oauth2User, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Oauth2User, err error)
	FindInBatches(result *[]*model.Oauth2User, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Oauth2User) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IOauth2UserDo
	Assign(attrs ...field.AssignExpr) IOauth2UserDo
	Joins(fields ...field.RelationField) IOauth2UserDo
	Preload(fields ...field.RelationField) IOauth2UserDo
	FirstOrInit() (*model.Oauth2User, error)
	FirstOrCreate() (*model.Oauth2User, error)
	FindByPage(offset int, limit int) (result []*model.Oauth2User, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IOauth2UserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (o oauth2UserDo) Debug() IOauth2UserDo {
	return o.withDO(o.DO.Debug())
}

func (o oauth2UserDo) WithContext(ctx context.Context) IOauth2UserDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o oauth2UserDo) ReadDB() IOauth2UserDo {
	return o.Clauses(dbresolver.Read)
}

func (o oauth2UserDo) WriteDB() IOauth2UserDo {
	return o.Clauses(dbresolver.Write)
}

func (o oauth2UserDo) Session(config *gorm.Session) IOauth2UserDo {
	return o.withDO(o.DO.Session(config))
}

func (o oauth2UserDo) Clauses(conds ...clause.Expression) IOauth2UserDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o oauth2UserDo) Returning(value interface{}, columns ...string) IOauth2UserDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o oauth2UserDo) Not(conds ...gen.Condition) IOauth2UserDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o oauth2UserDo) Or(conds ...gen.Condition) IOauth2UserDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o oauth2UserDo) Select(conds ...field.Expr) IOauth2UserDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o oauth2UserDo) Where(conds ...gen.Condition) IOauth2UserDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o oauth2UserDo) Order(conds ...field.Expr) IOauth2UserDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o oauth2UserDo) Distinct(cols ...field.Expr) IOauth2UserDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o oauth2UserDo) Omit(cols ...field.Expr) IOauth2UserDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o oauth2UserDo) Join(table schema.Tabler, on ...field.Expr) IOauth2UserDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o oauth2UserDo) LeftJoin(table schema.Tabler, on ...field.Expr) IOauth2UserDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o oauth2UserDo) RightJoin(table schema.Tabler, on ...field.Expr) IOauth2UserDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o oauth2UserDo) Group(cols ...field.Expr) IOauth2UserDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o oauth2UserDo) Having(conds ...gen.Condition) IOauth2UserDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o oauth2UserDo) Limit(limit int) IOauth2UserDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o oauth2UserDo) Offset(offset int) IOauth2UserDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o oauth2UserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IOauth2UserDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o oauth2UserDo) Unscoped() IOauth2UserDo {
	return o.withDO(o.DO.Unscoped())
}

func (o oauth2UserDo) Create(values ...*model.Oauth2User) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o oauth2UserDo) CreateInBatches(values []*model.Oauth2User, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o oauth2UserDo) Save(values ...*model.Oauth2User) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o oauth2UserDo) First() (*model.Oauth2User, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Oauth2User), nil
	}
}

func (o oauth2UserDo) Take() (*model.Oauth2User, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Oauth2User), nil
	}
}

func (o oauth2UserDo) Last() (*model.Oauth2User, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Oauth2User), nil
	}
}

func (o oauth2UserDo) Find() ([]*model.Oauth2User, error) {
	result, err := o.DO.Find()
	return result.([]*model.Oauth2User), err
}

func (o oauth2UserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Oauth2User, err error) {
	buf := make([]*model.Oauth2User, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o oauth2UserDo) FindInBatches(result *[]*model.Oauth2User, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o oauth2UserDo) Attrs(attrs ...field.AssignExpr) IOauth2UserDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o oauth2UserDo) Assign(attrs ...field.AssignExpr) IOauth2UserDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o oauth2UserDo) Joins(fields ...field.RelationField) IOauth2UserDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o oauth2UserDo) Preload(fields ...field.RelationField) IOauth2UserDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o oauth2UserDo) FirstOrInit() (*model.Oauth2User, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Oauth2User), nil
	}
}

func (o oauth2UserDo) FirstOrCreate() (*model.Oauth2User, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Oauth2User), nil
	}
}

func (o oauth2UserDo) FindByPage(offset int, limit int) (result []*model.Oauth2User, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o oauth2UserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o oauth2UserDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o oauth2UserDo) Delete(models ...*model.Oauth2User) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *oauth2UserDo) withDO(do gen.Dao) *oauth2UserDo {
	o.DO = *do.(*gen.DO)
	return o
}
