// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/yiran15/api-server/base/app"
	"github.com/yiran15/api-server/base/data"
	"github.com/yiran15/api-server/base/middleware"
	"github.com/yiran15/api-server/base/router"
	"github.com/yiran15/api-server/base/server"
	"github.com/yiran15/api-server/controller"
	"github.com/yiran15/api-server/pkg/casbin"
	"github.com/yiran15/api-server/pkg/jwt"
	"github.com/yiran15/api-server/pkg/local_cache"
	"github.com/yiran15/api-server/pkg/oauth"
	"github.com/yiran15/api-server/service/v1"
	"github.com/yiran15/api-server/store"
)

// Injectors from wire.go:

func InitApplication() (*app.Application, func(), error) {
	client, err := data.NewRDB()
	if err != nil {
		return nil, nil, err
	}
	cacheStore, cleanup, err := store.NewCacheStore(client)
	if err != nil {
		return nil, nil, err
	}
	generateToken, err := jwt.NewGenerateToken()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	oAuth2, err := oauth.NewOAuth2()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	cacher := localcache.NewCacher(oAuth2)
	userServicer := v1.NewUserService(cacheStore, generateToken, oAuth2, cacher)
	userController := controller.NewUserController(userServicer)
	db, cleanup2, err := data.NewDB()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	enforcer, err := casbin.NewEnforcer(db)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	casbinManager := casbin.NewCasbinManager(enforcer)
	roleServicer := v1.NewRoleService(casbinManager)
	roleController := controller.NewRoleController(roleServicer)
	apiServicer := v1.NewApiServicer()
	apiController := controller.NewApiController(apiServicer)
	authChecker := casbin.NewAuthChecker(enforcer)
	middlewareMiddleware := middleware.NewMiddleware(generateToken, authChecker, cacheStore)
	routerRouter := router.NewRouter(userController, roleController, apiController, middlewareMiddleware)
	engine, err := server.NewHttpServer(routerRouter)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	application := app.NewApplication(engine)
	return application, func() {
		cleanup2()
		cleanup()
	}, nil
}
